spring:
  application:
    name: payment-service

  datasource:
    # Prefer Heroku-provided JDBC vars, then DATABASE_URL, else local defaults
    url: ${JDBC_DATABASE_URL:${DATABASE_URL:jdbc:postgresql://localhost:5432/paymentdb}}
    username: ${JDBC_DATABASE_USERNAME:${DATABASE_USERNAME:payment_user}}
    password: ${JDBC_DATABASE_PASSWORD:${DATABASE_PASSWORD:payment_pass}}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never               # Set to 'always' for first run, then 'never'
      schema-locations: classpath:schema.sql

server:
  port: ${PORT:8081}            # Heroku injects PORT at runtime

razorpay:
  keyId: ${RAZORPAY_KEY_ID:}
  keySecret: ${RAZORPAY_KEY_SECRET:}
  webhookSecret: ${RAZORPAY_WEBHOOK_SECRET:}  #when verify webhooks
