spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: payment_user
    password: payment_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # dev only; use 'validate' in prod
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
